{
 "title": "Job",
 "tags": [ "version: main" ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "g_metrics_prefix", "label": "Metrics Prefix" },
   { "name": "g_cluster_name", "label": "Cluster", "query": { "query": "label_values(cluster_name)" } },
   {
    "name": "g_job_id",
    "label": "Job",
    "query": {
     "query": "label_values({cluster_name=\"$g_cluster_name\"},job_id)"
    }
   },
   {
    "name": "g_pod",
    "label": "Pod",
    "query": {
     "query": "label_values({cluster_name=\"$g_cluster_name\"},pod)"
    }
   },
   { "name": "g_nic_pod", "label": "NIC Pod", "query": { "query": "label_values(pod)" } },
   {
    "name": "g_eth_intf_name",
    "label": "Interface Name",
    "query": {
     "query": "label_values({pod=~\"$g_nic_pod\"},eth_intf_name)"
    }
   },
   {
    "name": "g_hostname",
    "label": "Hostname",
    "query": {
     "query": "label_values({cluster_name=\"$g_cluster_name\"},hostname)"
    }
   },
   {
    "name": "g_gpu_id",
    "label": "GPU ID",
    "query": {
     "query": "label_values({hostname=~\"$g_hostname\"},gpu_id)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "GPU Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Name",
     "type": "text",
     "description": "Name of the job ID or pod",
     "gridPos": { "h": 4, "w": 5, "x": 0, "y": 1 },
     "options": { "content": "${g_job_id}\n${g_pod}" }
    },
    {
     "title": "Memory Usage",
     "type": "stat",
     "description": "% of VRAM used across all GPUs this job or pod is running on",
     "gridPos": { "h": 4, "w": 3, "x": 5, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expression": "$A/$B", "type": "math" },
      { "expression": "$C/$D", "type": "math" }
     ]
    },
    {
     "title": "PCIe Max Speed",
     "type": "stat",
     "description": "Maximum PCIe speed",
     "gridPos": { "h": 3, "w": 4, "x": 8, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "MBs" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max(${g_metrics_prefix}pcie_max_speed{job_id!=\"\", job_id=\"$g_job_id\"})",
       "legendFormat": "{{job_id}}"
      },
      {
       "expr": "max(${g_metrics_prefix}pcie_max_speed{pod!=\"\", pod=\"$g_pod\"})",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "PCIe Counts",
     "type": "stat",
     "gridPos": { "h": 6, "w": 4, "x": 12, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(delta(${g_metrics_prefix}pcie_recovery_count{job_id!=\"\", job_id=\"$g_job_id\"}[$__interval]))",
       "legendFormat": "Recovery"
      },
      {
       "expr": "sum(delta(${g_metrics_prefix}pcie_recovery_count{pod!=\"\", pod=\"$g_pod\"}[$__interval]))",
       "legendFormat": "Recovery"
      },
      {
       "expr": "sum(delta(${g_metrics_prefix}pcie_replay_count{job_id!=\"\", job_id=\"$g_job_id\"}[$__interval]))",
       "legendFormat": "Replay"
      },
      {
       "expr": "sum(delta(${g_metrics_prefix}pcie_replay_count{pod!=\"\", pod=\"$g_pod\"}[$__interval]))",
       "legendFormat": "Replay"
      },
      {
       "expr": "sum(delta(${g_metrics_prefix}pcie_replay_rollover_count{job_id!=\"\", job_id=\"$g_job_id\"}[$__interval]))",
       "legendFormat": "Replay Rollover"
      },
      {
       "expr": "sum(delta(${g_metrics_prefix}pcie_replay_rollover_count{pod!=\"\", pod=\"$g_pod\"}[$__interval]))",
       "legendFormat": "Replay Rollover"
      },
      {
       "expr": "sum(delta(${g_metrics_prefix}pcie_nack_received_count{job_id!=\"\", job_id=\"$g_job_id\"}[$__interval]))",
       "legendFormat": "NACK Received"
      },
      {
       "expr": "sum(delta(${g_metrics_prefix}pcie_nack_received_count{pod!=\"\", pod=\"$g_pod\"}[$__interval]))",
       "legendFormat": "NACK Received"
      },
      {
       "expr": "sum(delta(${g_metrics_prefix}pcie_nack_sent_count{job_id!=\"\", job_id=\"$g_job_id\"}[$__interval]))",
       "legendFormat": "NACK Sent"
      },
      {
       "expr": "sum(delta(${g_metrics_prefix}pcie_nack_sent_count{pod!=\"\", pod=\"$g_pod\"}[$__interval]))",
       "legendFormat": "NACK Sent"
      }
     ]
    },
    {
     "title": "Top 5 GPU Usage",
     "type": "stat",
     "description": "Top 5 current GPU GFX Activity, labeled with hostname and GPU ID.",
     "gridPos": { "h": 12, "w": 4, "x": 16, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "max" ] } },
     "targets": [
      {
       "expr": "topk(5, ${g_metrics_prefix}gpu_gfx_activity{job_id!=\"\", job_id=\"$g_job_id\", card_model=~\"102-D65208-0C|102-D67305-00|102-D65209-0C\"})",
       "legendFormat": "{{hostname}} | {{gpu_id}} | {{xcc_index}}"
      },
      {
       "expr": "topk(5, ${g_metrics_prefix}gpu_gfx_busy_instantaneous{job_id!=\"\", job_id=\"$g_job_id\", card_model!~\"102-D65208-0C|102-D67305-00|102-D65209-0C\"})",
       "legendFormat": "{{hostname}} | {{gpu_id}} | {{xcc_index}}"
      },
      {
       "expr": "topk(5, ${g_metrics_prefix}gpu_gfx_activity{pod!=\"\", pod=\"$g_pod\", card_model=~\"102-D65208-0C|102-D67305-00|102-D65209-0C\"})",
       "legendFormat": "{{hostname}} | {{gpu_id}} | {{xcc_index}}"
      },
      {
       "expr": "topk(5, ${g_metrics_prefix}gpu_gfx_busy_instantaneous{pod!=\"\", pod=\"$g_pod\", card_model!~\"102-D65208-0C|102-D67305-00|102-D65209-0C\"})",
       "legendFormat": "{{hostname}} | {{gpu_id}} | {{xcc_index}}"
      }
     ]
    },
    {
     "title": "Top 5 Used VRAM",
     "type": "stat",
     "description": "Top 5 GPUs with highest VRAM used, labeled with hostname and GPU ID.",
     "gridPos": { "h": 12, "w": 4, "x": 20, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "decmbytes" } },
     "options": { "reduceOptions": { "calcs": [ "max" ] } },
     "targets": [
      {
       "expr": "topk(5, ${g_metrics_prefix}gpu_used_vram{job_id!=\"\", job_id=\"$g_job_id\"})",
       "legendFormat": "{{hostname}} | {{gpu_id}} | {{xcc_index}}"
      },
      {
       "expr": "topk(5, ${g_metrics_prefix}gpu_used_vram{pod!=\"\", pod=\"$g_pod\"})",
       "legendFormat": "{{hostname}} | {{gpu_id}} | {{xcc_index}}"
      }
     ]
    },
    {
     "title": "Total Current PCIe Bandwidth",
     "type": "stat",
     "description": "Total current PCIe bandwidth",
     "gridPos": { "h": 3, "w": 4, "x": 8, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "MBs" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(${g_metrics_prefix}pcie_bandwidth{job_id!=\"\", job_id=\"$g_job_id\"})",
       "legendFormat": "PCIe Bandwidth"
      },
      {
       "expr": "sum(${g_metrics_prefix}pcie_bandwidth{pod!=\"\", pod=\"$g_pod\"})",
       "legendFormat": "PCIe Bandwidth"
      }
     ]
    },
    {
     "title": "Compute Nodes",
     "type": "stat",
     "description": "\\# of compute nodes used by the job",
     "gridPos": { "h": 4, "w": 3, "x": 0, "y": 29 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(group by(hostname) (${g_metrics_prefix}gpu_gfx_activity{job_id!=\"\", job_id=\"$g_job_id\", card_model=~\"102-D65208-0C|102-D67305-00|102-D65209-0C\"}))",
       "legendFormat": "# of compute nodes used"
      },
      {
       "expr": "sum(group by(hostname) (${g_metrics_prefix}gpu_gfx_busy_instantaneous{job_id!=\"\", job_id=\"$g_job_id\", card_model!~\"102-D65208-0C|102-D67305-00|102-D65209-0C\"}))",
       "legendFormat": "# of compute nodes used"
      },
      {
       "expr": "sum(group by(hostname) (${g_metrics_prefix}gpu_gfx_activity{pod!=\"\", pod=\"$g_pod\", card_model=~\"102-D65208-0C|102-D67305-00|102-D65209-0C\"}))",
       "legendFormat": "# of compute nodes used"
      },
      {
       "expr": "sum(group by(hostname) (${g_metrics_prefix}gpu_gfx_busy_instantaneous{pod!=\"\", pod=\"$g_pod\", card_model!~\"102-D65208-0C|102-D67305-00|102-D65209-0C\"}))",
       "legendFormat": "# of compute nodes used"
      }
     ]
    },
    {
     "title": "Total Power Usage",
     "type": "stat",
     "description": "Total package power usage, in Watts",
     "gridPos": { "h": 4, "w": 5, "x": 3, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "watt" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expression": "$A+$B+$C+$D", "type": "math" }
     ]
    },
    {
     "title": "Total PCIe Bandwidth",
     "type": "timeseries",
     "description": "Total PCIe bandwidth over time",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "MBs" } },
     "targets": [
      {
       "expr": "sum(${g_metrics_prefix}pcie_bandwidth{job_id!=\"\", job_id=\"$g_job_id\"})",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum(${g_metrics_prefix}pcie_bandwidth{pod!=\"\", pod=\"$g_pod\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Allocated GPUs",
     "type": "stat",
     "description": "\\# of GPUs allocated by the job",
     "gridPos": { "h": 4, "w": 3, "x": 0, "y": 33 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(group by(gpu_uuid) (${g_metrics_prefix}gpu_gfx_activity{job_id!=\"\", job_id=\"$g_job_id\", card_model=~\"102-D65208-0C|102-D67305-00|102-D65209-0C\"}))",
       "legendFormat": "Allocated by Jobs"
      },
      {
       "expr": "sum(group by(gpu_uuid) (${g_metrics_prefix}gpu_gfx_busy_instantaneous{job_id!=\"\", job_id=\"$g_job_id\", card_model!~\"102-D65208-0C|102-D67305-00|102-D65209-0C\"}))",
       "legendFormat": "Allocated by Jobs"
      },
      {
       "expr": "sum(group by(gpu_uuid) (${g_metrics_prefix}gpu_gfx_activity{pod!=\"\", pod=\"$g_pod\", card_model=~\"102-D65208-0C|102-D67305-00|102-D65209-0C\"}))",
       "legendFormat": "Allocated by Pods"
      },
      {
       "expr": "sum(group by(gpu_uuid) (${g_metrics_prefix}gpu_gfx_busy_instantaneous{pod!=\"\", pod=\"$g_pod\", card_model!~\"102-D65208-0C|102-D67305-00|102-D65209-0C\"}))",
       "legendFormat": "Allocated by Pods"
      },
      {
       "expr": "sum(group by(gpu_id) (${g_metrics_prefix}gpu_gfx_activity{job_id!=\"\", job_id=\"$g_job_id\", card_model=~\"102-D65208-0C|102-D67305-00|102-D65209-0C\"} > 0))",
       "legendFormat": "Busy GPUs"
      },
      {
       "expr": "sum(group by(gpu_id) (${g_metrics_prefix}gpu_gfx_busy_instantaneous{job_id!=\"\", job_id=\"$g_job_id\", card_model!~\"102-D65208-0C|102-D67305-00|102-D65209-0C\"} > 0))",
       "legendFormat": "Busy GPUs"
      },
      {
       "expr": "sum(group by(gpu_id) (${g_metrics_prefix}gpu_gfx_activity{pod!=\"\", pod=\"$g_pod\", card_model=~\"102-D65208-0C|102-D67305-00|102-D65209-0C\"} > 0))",
       "legendFormat": "Busy GPUs"
      },
      {
       "expr": "sum(group by(gpu_id) (${g_metrics_prefix}gpu_gfx_busy_instantaneous{pod!=\"\", pod=\"$g_pod\", card_model!~\"102-D65208-0C|102-D67305-00|102-D65209-0C\"} > 0))",
       "legendFormat": "Busy GPUs"
      },
      {
       "expr": "sum(group by(gpu_uuid) (${g_metrics_prefix}gpu_health{job_id!=\"\", job_id=\"$g_job_id\"} < 1))",
       "legendFormat": "Unhealthy GPUs"
      },
      {
       "expr": "sum(group by(gpu_uuid) (${g_metrics_prefix}gpu_health{pod!=\"\", pod=\"$g_pod\"} < 1))",
       "legendFormat": "Unhealthy GPUs"
      }
     ]
    },
    {
     "title": "Total ECC Counts",
     "type": "stat",
     "gridPos": { "h": 4, "w": 5, "x": 3, "y": 33 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(delta(${g_metrics_prefix}gpu_ecc_correct_total{job_id!=\"\", job_id=\"$g_job_id\"}[$__interval]))",
       "legendFormat": "Correctable"
      },
      {
       "expr": "sum(delta(${g_metrics_prefix}gpu_ecc_correct_total{pod!=\"\", pod=\"$g_pod\"}[$__interval]))",
       "legendFormat": "Correctable"
      },
      {
       "expr": "sum(delta(${g_metrics_prefix}gpu_ecc_uncorrect_total{job_id!=\"\", job_id=\"$g_job_id\"}[$__interval]))",
       "legendFormat": "Uncorrectable"
      },
      {
       "expr": "sum(delta(${g_metrics_prefix}gpu_ecc_uncorrect_total{pod!=\"\", pod=\"$g_pod\"}[$__interval]))",
       "legendFormat": "Uncorrectable"
      }
     ]
    },
    {
     "title": "Average GPU Usage",
     "type": "timeseries",
     "description": "Average of current GFX activity",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 37 },
     "targets": [
      {
       "expr": "avg(${g_metrics_prefix}gpu_gfx_activity{job_id!=\"\", job_id=\"$g_job_id\", card_model=~\"102-D65208-0C|102-D67305-00|102-D65209-0C\"})",
       "legendFormat": "__auto"
      },
      {
       "expr": "avg(${g_metrics_prefix}gpu_gfx_activity{pod!=\"\", pod=\"$g_pod\", card_model=~\"102-D65208-0C|102-D67305-00|102-D65209-0C\"})",
       "legendFormat": "__auto"
      },
      {
       "expr": "avg(${g_metrics_prefix}gpu_gfx_busy_instantaneous{job_id!=\"\", job_id=\"$g_job_id\", card_model!~\"102-D65208-0C|102-D67305-00|102-D65209-0C\"})",
       "legendFormat": "__auto"
      },
      {
       "expr": "avg(${g_metrics_prefix}gpu_gfx_busy_instantaneous{pod!=\"\", pod=\"$g_pod\", card_model!~\"102-D65208-0C|102-D67305-00|102-D65209-0C\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Used VRAM",
     "type": "timeseries",
     "description": "% of used VRAM across GPUs the job or pod is running on",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      { "expression": "$A/$B", "type": "math" },
      { "expression": "$C/$D", "type": "math" }
     ]
    },
    {
     "title": "Average GPU Power",
     "type": "timeseries",
     "description": "Average GPU package power",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "watt" } },
     "targets": [
      {
       "expr": "avg(${g_metrics_prefix}gpu_package_power{job_id!=\"\", job_id=\"$g_job_id\", card_model=~\"102-G30211-00|102-G30211-0C|102-G30211-4C|102-G30212-0C|102-G30213-00|102-G30213-0C|102-G39205-00|102-G36220-0C|102-G36221-0C|102-G39206-00\"})",
       "legendFormat": "__auto"
      },
      {
       "expr": "avg(${g_metrics_prefix}gpu_package_power{pod!=\"\", pod=\"$g_pod\", card_model=~\"102-G30211-00|102-G30211-0C|102-G30211-4C|102-G30212-0C|102-G30213-00|102-G30213-0C|102-G39205-00|102-G36220-0C|102-G36221-0C|102-G39206-00\"})",
       "legendFormat": "__auto"
      },
      {
       "expr": "avg(${g_metrics_prefix}gpu_average_package_power{job_id!=\"\", job_id=\"$g_job_id\", card_model!~\"102-G30211-00|102-G30211-0C|102-G30211-4C|102-G30212-0C|102-G30213-00|102-G30213-0C|102-G39205-00|102-G36220-0C|102-G36221-0C|102-G39206-00\"})",
       "legendFormat": "__auto"
      },
      {
       "expr": "avg(${g_metrics_prefix}gpu_average_package_power{pod!=\"\", pod=\"$g_pod\", card_model!~\"102-G30211-00|102-G30211-0C|102-G30211-4C|102-G30212-0C|102-G30213-00|102-G30213-0C|102-G39205-00|102-G36220-0C|102-G36221-0C|102-G39206-00\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Average GPU Temperature",
     "type": "timeseries",
     "description": "Average of temperature of currently used GPUs",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "targets": [
      {
       "expr": "avg(${g_metrics_prefix}gpu_edge_temperature{job_id!=\"\", job_id=\"$g_job_id\", card_model!~\"102-G30211-00|102-G30211-0C|102-G30211-4C|102-G30212-0C|102-G30213-00|102-G30213-0C|102-G39205-00|102-G36220-0C|102-G36221-0C|102-G39206-00\"})",
       "legendFormat": "__auto"
      },
      {
       "expr": "avg(${g_metrics_prefix}gpu_edge_temperature{pod!=\"\", pod=\"$g_pod\", card_model!~\"102-G30211-00|102-G30211-0C|102-G30211-4C|102-G30212-0C|102-G30213-00|102-G30213-0C|102-G39205-00|102-G36220-0C|102-G36221-0C|102-G39206-00\"})",
       "legendFormat": "__auto"
      },
      {
       "expr": "avg(${g_metrics_prefix}gpu_junction_temperature{job_id!=\"\", job_id=\"$g_job_id\", card_model=~\"102-G30211-00|102-G30211-0C|102-G30211-4C|102-G30212-0C|102-G30213-00|102-G30213-0C|102-G39205-00|102-G36220-0C|102-G36221-0C|102-G39206-00\"})",
       "legendFormat": "__auto"
      },
      {
       "expr": "avg(${g_metrics_prefix}gpu_junction_temperature{pod!=\"\", pod=\"$g_pod\", card_model=~\"102-G30211-00|102-G30211-0C|102-G30211-4C|102-G30212-0C|102-G30213-00|102-G30213-0C|102-G39205-00|102-G36220-0C|102-G36221-0C|102-G39206-00\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Average Memory Temperature",
     "type": "timeseries",
     "description": "Average memory temperature of currently used GPUs",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "targets": [
      {
       "expr": "avg(${g_metrics_prefix}gpu_memory_temperature{job_id!=\"\", job_id=\"$g_job_id\"})",
       "legendFormat": "__auto"
      },
      {
       "expr": "avg(${g_metrics_prefix}gpu_memory_temperature{pod!=\"\", pod=\"$g_pod\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Average Sensor Temperatures",
     "type": "timeseries",
     "description": "Averages of current temperatures across GPUs used by the job or pod, in Celsius:\n- 4 HBM temperatures\n- Edge temperature\n- Junction/hotspot temperature",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 43 },
     "targets": [
      {
       "expr": "avg(${g_metrics_prefix}gpu_hbm_temperature{job_id!=\"\", job_id=\"$g_job_id\"})",
       "legendFormat": "HBM Temperature"
      },
      {
       "expr": "avg(${g_metrics_prefix}gpu_edge_temperature{job_id!=\"\", job_id=\"$g_job_id\"})",
       "legendFormat": "Edge Temperature"
      },
      {
       "expr": "avg(${g_metrics_prefix}gpu_junction_temperature{job_id!=\"\", job_id=\"$g_job_id\"})",
       "legendFormat": "Junction Temperature"
      },
      {
       "expr": "avg(${g_metrics_prefix}gpu_hbm_temperature{pod!=\"\", pod=\"$g_pod\"})",
       "legendFormat": "HBM Temperature"
      },
      {
       "expr": "avg(${g_metrics_prefix}gpu_edge_temperature{pod!=\"\", pod=\"$g_pod\"})",
       "legendFormat": "Edge Temperature"
      },
      {
       "expr": "avg(${g_metrics_prefix}gpu_junction_temperature{pod!=\"\", pod=\"$g_pod\"})",
       "legendFormat": "Junction Temperature"
      }
     ]
    },
    {
     "title": "All GPUs",
     "type": "table",
     "description": "List of all GPUs used by this job. Health is the last known status of the GPU during a running job in the selected time range.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
     "targets": [
      {
       "expr": "${g_metrics_prefix}gpu_health{job_id!=\"\", job_id=\"$g_job_id\"} or vector(0)",
       "legendFormat": "__auto"
      },
      {
       "expr": "${g_metrics_prefix}gpu_health{pod!=\"\", pod=\"$g_pod\"} or vector(0)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "GPU Performance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "SM Active",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "${g_metrics_prefix}gpu_prof_sm_active{pod!=\"\", pod=\"$g_pod\", hostname=~\"$g_hostname\", gpu_id=~\"$g_gpu_id\"}",
       "legendFormat": "GPU: {{gpu_id}} - Job: {{pod}}"
      },
      {
       "expr": "${g_metrics_prefix}gpu_prof_sm_active{pod!=\"\", pod=\"$g_pod\", hostname=~\"$g_hostname\", gpu_id=~\"$g_gpu_id\"}",
       "legendFormat": "GPU: {{gpu_id}} - Job: {{pod}}"
      }
     ]
    },
    {
     "title": "Occupancy / Compute",
     "type": "timeseries",
     "description": "Mean wavefront occupancy per compute unit across all CUs. Average number of wavefronts resident on each CU including idle CUs. \n\nUnit: wavefronts \n\nHigher values indicate better GPU utilization and latency hiding capability.",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 2 },
     "targets": [
      {
       "expr": "${g_metrics_prefix}gpu_prof_occupancy_per_cu{pod!=\"\", pod=\"$g_pod\", hostname=~\"$g_hostname\", gpu_id=~\"$g_gpu_id\"}",
       "legendFormat": "GPU: {{gpu_id}} - Job: {{pod}}"
      },
      {
       "expr": "${g_metrics_prefix}gpu_prof_occupancy_per_cu{pod!=\"\", pod=\"$g_pod\", hostname=~\"$g_hostname\", gpu_id=~\"$g_gpu_id\"}",
       "legendFormat": "GPU: {{gpu_id}} - Job: {{pod}}"
      }
     ]
    },
    {
     "title": "SIMD Utilization",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "${g_metrics_prefix}gpu_prof_simd_utilization{pod!=\"\", pod=\"$g_pod\", hostname=~\"$g_hostname\", gpu_id=~\"$g_gpu_id\"}",
       "legendFormat": "GPU: {{gpu_id}} - Job: {{pod}}"
      },
      {
       "expr": "${g_metrics_prefix}gpu_prof_simd_utilization{pod!=\"\", pod=\"$g_pod\", hostname=~\"$g_hostname\", gpu_id=~\"$g_gpu_id\"}",
       "legendFormat": "GPU: {{gpu_id}} - Job: {{pod}}"
      }
     ]
    },
    {
     "title": "Tensor Active",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "${g_metrics_prefix}gpu_prof_tensor_active_percent{pod!=\"\", pod=\"$g_pod\", hostname=~\"$g_hostname\", gpu_id=~\"$g_gpu_id\"}",
       "legendFormat": "GPU: {{gpu_id}} - Job: {{pod}}"
      },
      {
       "expr": "${g_metrics_prefix}gpu_prof_tensor_active_percent{pod!=\"\", pod=\"$g_pod\", hostname=~\"$g_hostname\", gpu_id=~\"$g_gpu_id\"}",
       "legendFormat": "GPU: {{gpu_id}} - Job: {{pod}}"
      }
     ]
    },
    {
     "title": "Occupancy / Active Compute",
     "type": "timeseries",
     "description": "Mean wavefront occupancy per active compute unit. Average number of wavefronts resident on CUs that have at least one active wavefront. \n\nUnit: wavefronts \n\nCDNA2 CUs support up to 32 wavefronts (4 SIMDs x 8 wavefronts each). Higher occupancy helps hide memory latency.",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 32 },
     "targets": [
      {
       "expr": "${g_metrics_prefix}gpu_prof_occupancy_per_active_cu{pod!=\"\", pod=\"$g_pod\", hostname=~\"$g_hostname\", gpu_id=~\"$g_gpu_id\"}",
       "legendFormat": "GPU: {{gpu_id}} - Job: {{pod}}"
      },
      {
       "expr": "${g_metrics_prefix}gpu_prof_occupancy_per_active_cu{pod!=\"\", pod=\"$g_pod\", hostname=~\"$g_hostname\", gpu_id=~\"$g_gpu_id\"}",
       "legendFormat": "GPU: {{gpu_id}} - Job: {{pod}}"
      }
     ]
    },
    {
     "title": "GUI Utilization",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "${g_metrics_prefix}gpu_prof_gui_util_percent{pod!=\"\", pod=\"$g_pod\", hostname=~\"$g_hostname\", gpu_id=~\"$g_gpu_id\"}",
       "legendFormat": "GPU: {{gpu_id}} - Job: {{pod}}"
      },
      {
       "expr": "${g_metrics_prefix}gpu_prof_gui_util_percent{pod!=\"\", pod=\"$g_pod\", hostname=~\"$g_hostname\", gpu_id=~\"$g_gpu_id\"}",
       "legendFormat": "GPU: {{gpu_id}} - Job: {{pod}}"
      }
     ]
    }
   ]
  },
  { "title": "LIFs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "title": "Total Packet Counts",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(delta(${g_metrics_prefix}nic_lif_stats_rx_unicast_packets{pod=~\"$g_nic_pod\"}[$__interval]))",
     "legendFormat": "RX"
    },
    {
     "expr": "sum(${g_metrics_prefix}nic_lif_stats_rx_unicast_packets{pod=~\"$g_nic_pod\"})",
     "legendFormat": "RX (Total)"
    },
    {
     "expr": "sum(delta(${g_metrics_prefix}nic_lif_stats_tx_unicast_packets{pod=~\"$g_nic_pod\"}[$__interval]))",
     "legendFormat": "TX"
    },
    {
     "expr": "sum(${g_metrics_prefix}nic_lif_stats_tx_unicast_packets{pod=~\"$g_nic_pod\"})",
     "legendFormat": "TX (Total)"
    }
   ]
  },
  {
   "title": "RX - Average Drops",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 3, "y": 3 },
   "targets": [
    {
     "expr": "avg(${g_metrics_prefix}nic_lif_stats_rx_broadcast_drop_packets{pod=~\"$g_nic_pod\"})",
     "legendFormat": "Broadcast Drop Packets"
    },
    {
     "expr": "avg(${g_metrics_prefix}nic_lif_stats_rx_multicast_drop_packets{pod=~\"$g_nic_pod\"})",
     "legendFormat": "Multicast Drop Packets"
    },
    {
     "expr": "avg(${g_metrics_prefix}nic_lif_stats_rx_unicast_drop_packets{pod=~\"$g_nic_pod\"})",
     "legendFormat": "Unicast Drop Packets"
    }
   ]
  },
  {
   "title": "TX - Average Drops",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 10, "y": 3 },
   "targets": [
    {
     "expr": "avg(${g_metrics_prefix}nic_lif_stats_tx_broadcast_drop_packets{pod=~\"$g_nic_pod\"})",
     "legendFormat": "Broadcast Drop Packets"
    },
    {
     "expr": "avg(${g_metrics_prefix}nic_lif_stats_tx_multicast_drop_packets{pod=~\"$g_nic_pod\"})",
     "legendFormat": "Multicast Drop Packets"
    },
    {
     "expr": "avg(${g_metrics_prefix}nic_lif_stats_tx_unicast_drop_packets{pod=~\"$g_nic_pod\"})",
     "legendFormat": "Unicast Drop Packets"
    }
   ]
  },
  {
   "title": "Average DMA Errors",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 3 },
   "targets": [
    {
     "expr": "avg(${g_metrics_prefix}nic_lif_stats_rx_dma_errors{pod=~\"$g_nic_pod\"})",
     "legendFormat": "RX"
    },
    {
     "expr": "avg(${g_metrics_prefix}nic_lif_stats_tx_dma_errors{pod=~\"$g_nic_pod\"})",
     "legendFormat": "TX"
    }
   ]
  },
  { "title": "RDMA", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "RX Packet Counts",
   "type": "stat",
   "description": "CN - Congestion Notification\nECN - Explicit Congestion Notification",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(delta(${g_metrics_prefix}rdma_rx_ucast_pkts{pod!=\"\", pod=~\"$g_nic_pod\"}[$__interval]))",
     "legendFormat": "Unicast Packets"
    },
    {
     "expr": "sum(${g_metrics_prefix}rdma_rx_ucast_pkts{pod!=\"\", pod=~\"$g_nic_pod\"})",
     "legendFormat": "Unicast Packets (Total)"
    },
    {
     "expr": "sum(delta(${g_metrics_prefix}rdma_rx_cnp_pkts{pod!=\"\", pod=~\"$g_nic_pod\"}[$__interval]))",
     "legendFormat": "CN Packets"
    },
    {
     "expr": "sum(${g_metrics_prefix}rdma_rx_cnp_pkts{pod!=\"\", pod=~\"$g_nic_pod\"})",
     "legendFormat": "CN Packets (Total)"
    },
    {
     "expr": "sum(delta(${g_metrics_prefix}rdma_rx_ecn_pkts{pod!=\"\", pod=~\"$g_nic_pod\"}[$__interval]))",
     "legendFormat": "ECN Packets"
    },
    {
     "expr": "sum(${g_metrics_prefix}rdma_rx_ecn_pkts{pod!=\"\", pod=~\"$g_nic_pod\"})",
     "legendFormat": "ECN Packets (Total)"
    }
   ]
  },
  {
   "title": "TX Packet Counts",
   "type": "stat",
   "description": "CN - Congestion Notification",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(delta(${g_metrics_prefix}rdma_tx_ucast_pkts{pod!=\"\", pod=~\"$g_nic_pod\"}[$__interval]))",
     "legendFormat": "Unicast Packets"
    },
    {
     "expr": "sum(${g_metrics_prefix}rdma_tx_ucast_pkts{pod!=\"\", pod=~\"$g_nic_pod\"})",
     "legendFormat": "Unicast Packets (Total)"
    },
    {
     "expr": "sum(delta(${g_metrics_prefix}rdma_tx_cnp_pkts{pod!=\"\", pod=~\"$g_nic_pod\"}[$__interval]))",
     "legendFormat": "CN Packets"
    },
    {
     "expr": "sum(${g_metrics_prefix}rdma_tx_cnp_pkts{pod!=\"\", pod=~\"$g_nic_pod\"})",
     "legendFormat": "CN Packets (Total)"
    }
   ]
  },
  {
   "title": "RX Request Errors",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "{__name__=~\".*rdma_req_rx_.*\", pod=~\"$g_nic_pod\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "TX Request Errors",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "targets": [
    {
     "expr": "{__name__=~\".*rdma_req_tx_.*\", pod=~\"$g_nic_pod\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RX Response Errors",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "{__name__=~\".*rdma_resp_rx_.*\", pod=~\"$g_nic_pod\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "TX Response Errors",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 21 },
   "targets": [
    {
     "expr": "{__name__=~\".*rdma_resp_tx_.*\", pod=~\"$g_nic_pod\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "ethtool", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "RX Counts",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 29 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(delta(${g_metrics_prefix}eth_rx_bytes{pod!=\"\", pod=~\"$g_nic_pod\"}[$__interval]))",
     "legendFormat": "Bytes"
    },
    {
     "expr": "sum(${g_metrics_prefix}eth_rx_bytes{pod!=\"\", pod=~\"$g_nic_pod\"})",
     "legendFormat": "Bytes (Total)"
    },
    {
     "expr": "sum(delta(${g_metrics_prefix}eth_rx_packets{pod!=\"\", pod=~\"$g_nic_pod\"}[$__interval]))",
     "legendFormat": "Packets"
    },
    {
     "expr": "sum(${g_metrics_prefix}eth_rx_packets{pod!=\"\", pod=~\"$g_nic_pod\"})",
     "legendFormat": "Packets (Total)"
    },
    {
     "expr": "sum(delta(${g_metrics_prefix}eth_hw_rx_dropped{pod!=\"\", pod=~\"$g_nic_pod\"}[$__interval]))",
     "legendFormat": "HW Dropped Frames"
    },
    {
     "expr": "sum(${g_metrics_prefix}eth_hw_rx_dropped{pod!=\"\", pod=~\"$g_nic_pod\"})",
     "legendFormat": "HW Dropped Frames (Total)"
    }
   ]
  },
  {
   "title": "TX Counts",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 29 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(delta(${g_metrics_prefix}eth_tx_bytes{pod!=\"\", pod=~\"$g_nic_pod\"}[$__interval]))",
     "legendFormat": "Bytes"
    },
    {
     "expr": "sum(${g_metrics_prefix}eth_tx_bytes{pod!=\"\", pod=~\"$g_nic_pod\"})",
     "legendFormat": "Bytes (Total)"
    },
    {
     "expr": "sum(delta(${g_metrics_prefix}eth_tx_packets{pod!=\"\", pod=~\"$g_nic_pod\"}[$__interval]))",
     "legendFormat": "Packets"
    },
    {
     "expr": "sum(${g_metrics_prefix}eth_tx_packets{pod!=\"\", pod=~\"$g_nic_pod\"})",
     "legendFormat": "Packets (Total)"
    },
    {
     "expr": "sum(delta(${g_metrics_prefix}eth_hw_tx_dropped{pod!=\"\", pod=~\"$g_nic_pod\"}[$__interval]))",
     "legendFormat": "HW Dropped Frames"
    },
    {
     "expr": "sum(${g_metrics_prefix}eth_hw_tx_dropped{pod!=\"\", pod=~\"$g_nic_pod\"})",
     "legendFormat": "HW Dropped Frames (Total)"
    }
   ]
  },
  {
   "title": "RX ethtool Frames",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "{__name__=~\".*eth_frames_rx_.*\", pod=~\"$g_nic_pod\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "TX ethtool Frames",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 33 },
   "targets": [
    {
     "expr": "{__name__=~\".*eth_frames_tx_.*\", pod=~\"$g_nic_pod\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RX ethtool Packets Dropped",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "{__name__=~\".*eth_rx_.*_dropped\", pod=~\"$g_nic_pod\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "LIF: $g_eth_intf_name",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 },
   "repeat": "g_eth_intf_name",
   "collapsed": true,
   "panels": [
    {
     "title": "Packet Counts",
     "type": "stat",
     "gridPos": { "h": 6, "w": 3, "x": 0, "y": 135 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(delta(${g_metrics_prefix}nic_lif_stats_rx_unicast_packets{pod=~\"$g_nic_pod\", eth_intf_name=\"$g_eth_intf_name\"}[$__interval]))",
       "legendFormat": "RX"
      },
      {
       "expr": "sum(${g_metrics_prefix}nic_lif_stats_rx_unicast_packets{pod=~\"$g_nic_pod\", eth_intf_name=\"$g_eth_intf_name\"})",
       "legendFormat": "RX (Total)"
      },
      {
       "expr": "sum(delta(${g_metrics_prefix}nic_lif_stats_tx_unicast_packets{pod=~\"$g_nic_pod\", eth_intf_name=\"$g_eth_intf_name\"}[$__interval]))",
       "legendFormat": "TX"
      },
      {
       "expr": "sum(${g_metrics_prefix}nic_lif_stats_tx_unicast_packets{pod=~\"$g_nic_pod\", eth_intf_name=\"$g_eth_intf_name\"})",
       "legendFormat": "TX (Total)"
      }
     ]
    },
    {
     "title": "RX - Drops",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 7, "x": 3, "y": 135 },
     "targets": [
      {
       "expr": "${g_metrics_prefix}nic_lif_stats_rx_broadcast_drop_packets{pod=~\"$g_nic_pod\", eth_intf_name=\"$g_eth_intf_name\"}",
       "legendFormat": "Broadcast Drop Packets"
      },
      {
       "expr": "${g_metrics_prefix}nic_lif_stats_rx_multicast_drop_packets{pod=~\"$g_nic_pod\", eth_intf_name=\"$g_eth_intf_name\"}",
       "legendFormat": "Multicast Drop Packets"
      },
      {
       "expr": "${g_metrics_prefix}nic_lif_stats_rx_unicast_drop_packets{pod=~\"$g_nic_pod\", eth_intf_name=\"$g_eth_intf_name\"}",
       "legendFormat": "Unicast Drop Packets"
      }
     ]
    },
    {
     "title": "TX - Drops",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 7, "x": 10, "y": 135 },
     "targets": [
      {
       "expr": "${g_metrics_prefix}nic_lif_stats_tx_broadcast_drop_packets{pod=~\"$g_nic_pod\", eth_intf_name=\"$g_eth_intf_name\"}",
       "legendFormat": "Broadcast Drop Packets"
      },
      {
       "expr": "${g_metrics_prefix}nic_lif_stats_tx_multicast_drop_packets{pod=~\"$g_nic_pod\", eth_intf_name=\"$g_eth_intf_name\"}",
       "legendFormat": "Multicast Drop Packets"
      },
      {
       "expr": "${g_metrics_prefix}nic_lif_stats_tx_unicast_drop_packets{pod=~\"$g_nic_pod\", eth_intf_name=\"$g_eth_intf_name\"}",
       "legendFormat": "Unicast Drop Packets"
      }
     ]
    },
    {
     "title": "DMA Errors",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 7, "x": 17, "y": 135 },
     "targets": [
      {
       "expr": "${g_metrics_prefix}nic_lif_stats_rx_dma_errors{pod=~\"$g_nic_pod\", eth_intf_name=\"$g_eth_intf_name\"}",
       "legendFormat": "RX"
      },
      {
       "expr": "${g_metrics_prefix}nic_lif_stats_tx_dma_errors{pod=~\"$g_nic_pod\", eth_intf_name=\"$g_eth_intf_name\"}",
       "legendFormat": "TX"
      }
     ]
    }
   ]
  }
 ]
}