{
 "title": "Overview",
 "description": "Overview of the system",
 "tags": [ "version: 1.4.1" ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "g_metrics_prefix", "label": "Metrics Prefix" },
   { "name": "g_gpu_uuids", "query": { "query": "label_values(GPU_UUID)" } },
   { "name": "g_job_ids", "query": { "query": "label_values(job_id)" } },
   { "name": "g_cluster_name", "label": "Cluster", "query": { "query": "label_values(cluster_name)" } }
  ]
 },
 "panels": [
  {
   "title": "GPUs",
   "type": "stat",
   "description": "Number of GPUs in the node",
   "gridPos": { "h": 6, "w": 2, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(${g_metrics_prefix}gpu_nodes_total{cluster_name=\"$g_cluster_name\"})",
     "legendFormat": "GPUs"
    },
    {
     "expr": "count(${g_metrics_prefix}gpu_health{cluster_name=\"$g_cluster_name\"} < 1)",
     "legendFormat": "Unhealthy GPUs"
    }
   ]
  },
  {
   "title": "Jobs",
   "type": "stat",
   "description": "Number of jobs",
   "gridPos": { "h": 6, "w": 2, "x": 2, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(group by(job_id) (${g_metrics_prefix}gpu_gfx_activity{cluster_name=\"$g_cluster_name\", job_id!=\"\", card_model=~\"102-D65208-0C|102-D67305-00|102-D65209-0C\"}))",
     "legendFormat": "Jobs"
    },
    {
     "expr": "sum(group by(job_id) (${g_metrics_prefix}gpu_gfx_busy_instantaneous{cluster_name=\"$g_cluster_name\", job_id!=\"\", card_model!~\"102-D65208-0C|102-D67305-00|102-D65209-0C\"}))",
     "legendFormat": "Jobs"
    },
    {
     "expr": "sum(group by(pod) (${g_metrics_prefix}gpu_gfx_activity{cluster_name=\"$g_cluster_name\", pod!=\"\", card_model=~\"102-D65208-0C|102-D67305-00|102-D65209-0C\"}))",
     "legendFormat": "Pods"
    },
    {
     "expr": "sum(group by(pod) (${g_metrics_prefix}gpu_gfx_busy_instantaneous{cluster_name=\"$g_cluster_name\", pod!=\"\", card_model!~\"102-D65208-0C|102-D67305-00|102-D65209-0C\"}))",
     "legendFormat": "Pods"
    }
   ]
  },
  {
   "title": "Total Power Usage",
   "type": "stat",
   "description": "Total power usage, in Watts",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "$A+$B", "type": "math" }
   ]
  },
  {
   "title": "PCIe Max Speed",
   "type": "stat",
   "description": "Current maximum PCIe speed",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "MBs" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count_values(\"count\", ${g_metrics_prefix}pcie_max_speed{cluster_name=\"$g_cluster_name\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "PCIe Counts",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(delta(${g_metrics_prefix}pcie_recovery_count{cluster_name=\"$g_cluster_name\"}[$__interval]))",
     "legendFormat": "Recovery"
    },
    {
     "expr": "sum(delta(${g_metrics_prefix}pcie_replay_count{cluster_name=\"$g_cluster_name\"}[$__interval]))",
     "legendFormat": "Replay"
    },
    {
     "expr": "sum(delta(${g_metrics_prefix}pcie_replay_rollover_count{cluster_name=\"$g_cluster_name\"}[$__interval]))",
     "legendFormat": "Replay Rollover"
    },
    {
     "expr": "sum(delta(${g_metrics_prefix}pcie_nack_received_count{cluster_name=\"$g_cluster_name\"}[$__interval]))",
     "legendFormat": "NACK Received"
    },
    {
     "expr": "sum(delta(${g_metrics_prefix}pcie_nack_sent_count{cluster_name=\"$g_cluster_name\"}[$__interval]))",
     "legendFormat": "NACK Sent"
    }
   ]
  },
  {
   "title": "Top 5 GPU Usage",
   "type": "stat",
   "description": "Top 5 current GPU GFX Activity, labeled with hostname, GPU ID, and job ID.",
   "gridPos": { "h": 12, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk by() (5, ${g_metrics_prefix}gpu_gfx_activity{cluster_name=\"$g_cluster_name\", card_model=~\"102-D65208-0C|102-D67305-00|102-D65209-0C\"})",
     "legendFormat": "{{hostname}} | {{gpu_id}} | {{gpu_partition_id}} | {{job_id}}{{pod}}"
    },
    {
     "expr": "topk by() (5, ${g_metrics_prefix}gpu_gfx_busy_instantaneous{cluster_name=\"$g_cluster_name\", card_model!~\"102-D65208-0C|102-D67305-00|102-D65209-0C\"})",
     "legendFormat": "{{hostname}} | {{gpu_id}} | {{gpu_partition_id}} | {{job_id}}{{pod}}"
    }
   ]
  },
  {
   "title": "Top 5 Used VRAM",
   "type": "stat",
   "description": "Top 5 GPUs with highest VRAM used, labeled with hostname and GPU ID.",
   "gridPos": { "h": 12, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(5, ${g_metrics_prefix}gpu_used_vram{cluster_name=\"$g_cluster_name\"})",
     "legendFormat": "{{hostname}} | {{gpu_id}}"
    }
   ]
  },
  {
   "title": "Current Total PCIe Bandwidth",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "MBs" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(${g_metrics_prefix}pcie_bandwidth{cluster_name=\"$g_cluster_name\"})",
     "legendFormat": "Total current PCIe bandwidth"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(${g_metrics_prefix}gpu_used_vram{cluster_name=\"$g_cluster_name\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(${g_metrics_prefix}gpu_total_vram{cluster_name=\"$g_cluster_name\"})",
     "legendFormat": "__auto"
    },
    { "expression": "($A / $B) * 100", "type": "math" }
   ]
  },
  {
   "title": "Allocated GPUs",
   "type": "stat",
   "description": "\\# of GPUs allocated by jobs",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(group by(gpu_uuid) (${g_metrics_prefix}gpu_gfx_activity{cluster_name=\"$g_cluster_name\", job_id!=\"\", card_model=~\"102-D65208-0C|102-D67305-00|102-D65209-0C\"}))",
     "legendFormat": "Allocated by Jobs"
    },
    {
     "expr": "sum(group by(gpu_uuid) (${g_metrics_prefix}gpu_gfx_busy_instantaneous{cluster_name=\"$g_cluster_name\", job_id!=\"\", card_model!~\"102-D65208-0C|102-D67305-00|102-D65209-0C\"}))",
     "legendFormat": "Allocated by Jobs"
    },
    {
     "expr": "sum(group by(gpu_uuid) (${g_metrics_prefix}gpu_gfx_activity{cluster_name=\"$g_cluster_name\", pod!=\"\", card_model=~\"102-D65208-0C|102-D67305-00|102-D65209-0C\"}))",
     "legendFormat": "Allocated by Pods"
    },
    {
     "expr": "sum(group by(gpu_uuid) (${g_metrics_prefix}gpu_gfx_busy_instantaneous{cluster_name=\"$g_cluster_name\", pod!=\"\", card_model!~\"102-D65208-0C|102-D67305-00|102-D65209-0C\"}))",
     "legendFormat": "Allocated by Pods"
    },
    {
     "expr": "sum(group by(gpu_uuid) (${g_metrics_prefix}gpu_gfx_activity{cluster_name=\"$g_cluster_name\", card_model=~\"102-D65208-0C|102-D67305-00|102-D65209-0C\"} > 0))",
     "legendFormat": "Busy GPUs"
    },
    {
     "expr": "sum(group by(gpu_uuid) (${g_metrics_prefix}gpu_gfx_busy_instantaneous{cluster_name=\"$g_cluster_name\", card_model!~\"102-D65208-0C|102-D67305-00|102-D65209-0C\"} > 0))",
     "legendFormat": "Busy GPUs"
    }
   ]
  },
  {
   "title": "Total PCIe Bandwidth",
   "type": "timeseries",
   "description": "Total PCIe Bandwidth over time",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "MBs" } },
   "targets": [
    {
     "expr": "sum(${g_metrics_prefix}pcie_bandwidth{cluster_name=\"$g_cluster_name\"})",
     "legendFormat": "Total PCIe Bandwidth"
    }
   ]
  },
  {
   "title": "Energy Consumed",
   "type": "stat",
   "description": "Total accumulated energy consumed",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "joule" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(delta(${g_metrics_prefix}gpu_energy_consumed{cluster_name=\"$g_cluster_name\"}[$__interval]))",
     "legendFormat": "Accumulated Energy Consumed (nJ)"
    },
    { "expression": "$A / 1000000", "type": "math" }
   ]
  },
  {
   "title": "Average GPU Usage",
   "type": "timeseries",
   "description": "Average of current GPU GFX activity",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg(${g_metrics_prefix}gpu_gfx_activity{cluster_name=\"$g_cluster_name\", card_model=~\"102-D65208-0C|102-D67305-00|102-D65209-0C\"})",
     "legendFormat": "GPU Usage"
    },
    {
     "expr": "avg(${g_metrics_prefix}gpu_gfx_busy_instantaneous{cluster_name=\"$g_cluster_name\", card_model!~\"102-D65208-0C|102-D67305-00|102-D65209-0C\"})",
     "legendFormat": "GPU Usage"
    }
   ]
  },
  {
   "title": "Used VRAM",
   "type": "timeseries",
   "description": "Used VRAM over time",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "expression": "($A / $B) * 100", "type": "math" }
   ]
  },
  {
   "title": "Average GPU Power",
   "type": "timeseries",
   "description": "Average GPU package power, in Watts",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "avg(${g_metrics_prefix}gpu_package_power{cluster_name=\"$g_cluster_name\", card_model=~\"102-G30211-00|102-G30211-0C|102-G30211-4C|102-G30212-0C|102-G30213-00|102-G30213-0C\"})",
     "legendFormat": "GPU Power"
    },
    {
     "expr": "avg(${g_metrics_prefix}gpu_average_package_power{cluster_name=\"$g_cluster_name\", card_model!~\"102-G30211-00|102-G30211-0C|102-G30211-4C|102-G30212-0C|102-G30213-00|102-G30213-0C\"})",
     "legendFormat": "GPU Power"
    }
   ]
  },
  {
   "title": "Average GPU Usage of Allocated GPUs",
   "type": "timeseries",
   "description": "Average of current allocated GPU GFX activity",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg(${g_metrics_prefix}gpu_gfx_activity{cluster_name=\"$g_cluster_name\", job_id!=\"\", card_model=~\"102-D65208-0C|102-D67305-00|102-D65209-0C\"}) or avg(${g_metrics_prefix}gpu_gfx_activity{cluster_name=\"$g_cluster_name\", pod!=\"\", card_model=~\"102-D65208-0C|102-D67305-00|102-D65209-0C\"}) or avg(${g_metrics_prefix}gpu_gfx_busy_instantaneous{cluster_name=\"$g_cluster_name\", job_id!=\"\", card_model!~\"102-D65208-0C|102-D67305-00|102-D65209-0C\"}) or avg(${g_metrics_prefix}gpu_gfx_busy_instantaneous{cluster_name=\"$g_cluster_name\", pod!=\"\", card_model!~\"102-D65208-0C|102-D67305-00|102-D65209-0C\"}) or vector(0)",
     "legendFormat": "Allocated GPU Usage"
    }
   ]
  },
  {
   "title": "Average Memory Usage of Allocated GPUs",
   "type": "timeseries",
   "description": "Used VRAM of allocated GPUs over time",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "expression": "($A / $B) * 100", "type": "math" }
   ]
  },
  {
   "title": "Average Sensor Temperatures",
   "type": "timeseries",
   "description": "Average current temperatures, in Celsius, from:\n- HBM (4 sensors)\n- Edge\n- Junction/hotspot",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "avg(${g_metrics_prefix}gpu_hbm_temperature{cluster_name=\"$g_cluster_name\"})",
     "legendFormat": "HBM Temperature"
    },
    {
     "expr": "avg(${g_metrics_prefix}gpu_edge_temperature{cluster_name=\"$g_cluster_name\"})",
     "legendFormat": "Edge Temperature"
    },
    {
     "expr": "avg(${g_metrics_prefix}gpu_junction_temperature{cluster_name=\"$g_cluster_name\"})",
     "legendFormat": "Junction Temperature"
    }
   ]
  },
  {
   "title": "Average GPU Temperature",
   "type": "timeseries",
   "description": "Current temperature, in Celsius",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "avg(${g_metrics_prefix}gpu_edge_temperature{cluster_name=\"$g_cluster_name\", card_model!~\"102-G30211-00|102-G30211-0C|102-G30211-4C|102-G30212-0C|102-G30213-00|102-G30213-0C\"})",
     "legendFormat": "Edge Temperature"
    },
    {
     "expr": "avg(${g_metrics_prefix}gpu_junction_temperature{cluster_name=\"$g_cluster_name\", card_model=~\"102-G30211-00|102-G30211-0C|102-G30211-4C|102-G30212-0C|102-G30213-00|102-G30213-0C\"})",
     "legendFormat": "Junction Temperature"
    }
   ]
  },
  {
   "title": "Average Memory Temperature",
   "type": "timeseries",
   "description": "Current memory temperature, in Celsius",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "avg(${g_metrics_prefix}gpu_memory_temperature{cluster_name=\"$g_cluster_name\"})",
     "legendFormat": "Memory Temperature"
    }
   ]
  },
  {
   "title": "All GPUs",
   "type": "table",
   "description": "List of all GPUs.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
   "targets": [
    {
     "expr": "${g_metrics_prefix}gpu_health{cluster_name=\"$g_cluster_name\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}