---
version: 2.0
targets:
  e2e:
    commands: ["sh", "-c", "cd /usr/src/github.com/ROCm/device-metrics-exporter && EXPORTER_IMAGE_TAG=latest make e2e"]
    owners: ["email:prshanmug@amd.com"]
    logfiles:
        - /device-metrics-exporter/exporter.log

image:
  bind_dir: "/device-metrics-exporter"
  work_dir: "/device-metrics-exporter"

submodules: {}
